### ISSUE TITLE
关于flash下载算法的问题

### ISSUE THREAD

**Issue by jhembed** [XIVN1987/MCUProg#2]
你好博主，请问flash_code开头的这32字节是什么用处？0xE00ABE00, 0x062D780D, 0x24084068, 0xD3000040, 0x1E644058, 0x1C49D1FA, 0x2A001E52, 0x4770D1F2

**Comment by XIVN1987** [comment]
第一个字是 break 指令，，执行烧写算法函数时返回地址会指向它，，这样执行完烧写算法函数后返回时就会执行 break 指令，，导致目标 CPU 暂停，，等待上位机执行新的操作。。
后面七个字似乎没用。。

**Comment by gyh02133** [comment]
太久了，不记的，您是要什么下载？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XIVN1987/MCUProg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 下午2:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [XIVN1987/MCUProg] 关于flash下载算法的问题 (Issue #2)





 
第一个字是 break 指令，，执行烧写算法函数时返回地址会指向它，，这样执行完烧写算法函数后返回时就会执行 break 指令，，导致目标 CPU 暂停，，等待上位机执行新的操作。。
 后面七个字似乎没用。。
