### ISSUE TITLE
增加Release 

### ISSUE THREAD

**Issue by stig3** [XIVN1987/MCUProg#3]
能否增加pyinstall打包后的程序,方便大家安装使用

**Comment by XIVN1987** [comment]
这么做没意义。。因为 MCUProg 本身只支持几种芯片的烧写，，
只有在源码的基础上添加自己需要使用的芯片的烧写支持，，才有使用价值。。

这不是一个给用户使用的产品，，而是一个演示如何通过 python 代码控制 Jlink、DAPLink 烧写 MCU 的例程
